spring:
  application:
    name: omnimemo
  config:
    import: file:./application-secret.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/omnimemo
    username: omnimemo
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  web:
    resources:
      static-locations: classpath:/static/
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    encoding: UTF-8

server:
  port: 8080
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json

logging:
  level:
    root: INFO
    com.fj.omnimemo: DEBUG

app:
  security:
    token-ttl-seconds: 259200
    refresh-token-ttl-seconds: 1209600
